# Generated by Django 4.2.2 on 2023-06-06 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('munchkinOCRapp', '0002_others_delete_curse_delete_miscellaneous'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_pl', models.CharField(max_length=200, unique=True)),
                ('name_ru', models.CharField(max_length=200)),
                ('description_ru', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Curse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_pl', models.CharField(max_length=200, unique=True)),
                ('name_ru', models.CharField(max_length=200)),
                ('description_ru', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Hireling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_pl', models.CharField(max_length=200, unique=True)),
                ('name_ru', models.CharField(max_length=200)),
                ('description_ru', models.TextField()),
                ('bonus', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_pl', models.CharField(max_length=200, unique=True)),
                ('name_ru', models.CharField(max_length=200)),
                ('description_ru', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Steed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_pl', models.CharField(max_length=200, unique=True)),
                ('name_ru', models.CharField(max_length=200)),
                ('description_ru', models.TextField()),
                ('bonus', models.IntegerField()),
                ('is_big', models.BooleanField(default=False)),
                ('price', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameModel(
            old_name='Others',
            new_name='Misc',
        ),
        migrations.DeleteModel(
            name='Hirelings',
        ),
        migrations.DeleteModel(
            name='Steeds',
        ),
        migrations.RenameField(
            model_name='monster',
            old_name='is_two_levels',
            new_name='get_two_levels',
        ),
    ]
