# Generated by Django 4.2.2 on 2023-06-07 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('munchkinOCRapp', '0004_alter_monstermodifier_description_ru'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monstermodifier',
            name='description_ru',
        ),
        migrations.AlterField(
            model_name='class',
            name='description_ru',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='curse',
            name='description_ru',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='hireling',
            name='description_ru',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='misc',
            name='description_ru',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='monster',
            name='description_ru',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='race',
            name='description_ru',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='steed',
            name='description_ru',
            field=models.TextField(blank=True),
        ),
    ]
