# Generated by Django 4.2.2 on 2023-06-07 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('munchkinOCRapp', '0005_remove_monstermodifier_description_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monstermodifier',
            name='description_ru',
            field=models.TextField(blank=True),
        ),
    ]
